apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-postgresql
  namespace: bookreview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-postgresql
  template:
    metadata:
      labels:
        app: comment-postgresql
    spec:
      schedulerName: stork
      containers:
        - name: postgres-container
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: db-comment-secret       
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: comment-pvc