apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comment-pvc
  namespace: bookreview
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: px-sc