apiVersion: v1
kind: Secret
metadata:
  name: comment-secret
  namespace: bookreview
stringData:
  APP_PORT: "${APP_PORT}"
  DB_HOST: ${DB_HOST}
  DB_PORT: "${DB_PORT}"
  DB_INSTANCE: ${DB_INSTANCE}
  DB_UNAME: ${DB_UNAME}
  DB_PASS: ${DB_PASS}