apiVersion: v1
kind: Secret
metadata:
  name: holder-secret
  namespace: bookreview
data:
  id: NTMzMmNlMmUtNzVlMC0yMDgyLWUwNzktYzYwM2U0ZDlkNGIxCg==
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: bookreview
  name: bookreview-vault-connection
spec:
  address: https://172.21.53.100:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: bookreview
  name: bookreview-vault-auth
spec:
  vaultConnectionRef: bookreview-vault-connection
  method: appRole
  mount: approle-k8s
  namespace: admin
  appRole:
    roleId: 2c9763ca-ba8b-dc2f-f467-cec4d25a356d
    secretRef: holder-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: bookreview
  name: bookreview-comment-kv
spec:
  vaultAuthRef: bookreview-vault-auth
  mount: comment-prod
  type: kv-v2
  path: webapp/config
  refreshAfter: 5s
  namespace: admin
  destination:
    create: true
    name: comment-secret-deployment
  rolloutRestartTargets:
  - kind: Deployment
    name: comment