apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bookcomment-dev
  namespace: bookreview-dev
spec:
  path: /
  to:
    name: comment-svc
    weight: 100
    kind: Service
  port:
    targetPort: 8081
  host: bookcomment-dev-bookreview.apps-crc.testing
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIFFzCCA3+gAwIBAgIQAwcshWQKnVyhlqdfcexqLzANBgkqhkiG9w0BAQsFADCB
      ozEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMTwwOgYDVQQLDDNyYWNo
      bWF0YWRoaWVAQ3JhY2tlcnMtTWFjQm9vay5sb2NhbCAoUmFjaG1hdCBBZGhpZSkx
      QzBBBgNVBAMMOm1rY2VydCByYWNobWF0YWRoaWVAQ3JhY2tlcnMtTWFjQm9vay5s
      b2NhbCAoUmFjaG1hdCBBZGhpZSkwHhcNMjQwODA3MTY0MTMzWhcNMzQwODA3MTY0
      MTMzWjCBozEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMTwwOgYDVQQL
      DDNyYWNobWF0YWRoaWVAQ3JhY2tlcnMtTWFjQm9vay5sb2NhbCAoUmFjaG1hdCBB
      ZGhpZSkxQzBBBgNVBAMMOm1rY2VydCByYWNobWF0YWRoaWVAQ3JhY2tlcnMtTWFj
      Qm9vay5sb2NhbCAoUmFjaG1hdCBBZGhpZSkwggGiMA0GCSqGSIb3DQEBAQUAA4IB
      jwAwggGKAoIBgQCjqYuG8bGjMtJoKmgjmITXWDhfAlIwNdu6MdmqtPzIC5rpvfjq
      ux+ag6gi7NlF8xKhQ3IiNmlkZ9/T3dKOG9Y88CapGfvgv+FqOiwNby1zLTMcz5GP
      /2rqsRAZzWreZ8Bg+T3g32SLHCA/cymWz/o/FDPk+9ANwClGs0vjwpW8OQD79/qW
      4SxDZuxXsX+kWMVxUMm+zQ7voyZlCpP/gKZT1iDhOVRv4JRPfAVZpAqfinyW6blO
      UvTPZg17+pNLlCjMJfqTP6dhj8bqFkQtOsz8Cf/wND3W0/XNZPm3eznpccJ0kCg6
      dKMoDpTrDqNhHIofJHj+r5Lmkj6cTqJRxrcjUKrAah3xhh5eEcU4nx7ebvbqQ1Ba
      FPmVofmPLewhwvCegI7+uXGdPEmZww5uTcVDhzJ9a5bgeFhbfK54iN1KHQ6lxpil
      lbQK6B79/k3XssqjPijM/9U5M7zhN5/zj8H5MClHMxswXdXq6Dz9jMaR6cDkSF/M
      b5E4KJSdMbgFPXsCAwEAAaNFMEMwDgYDVR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQI
      MAYBAf8CAQAwHQYDVR0OBBYEFKp4NE+gYO2OldqVJJAeHGquqUA1MA0GCSqGSIb3
      DQEBCwUAA4IBgQA2jxIVc1jklJBNQ157dV2AJUOC1x3VLyfBvYJYQfX1gps26bAB
      RNDWMtmYrFxDKpF5JsSum84OJGU8zwfOc6Q3UJr2z72Wc3wP6268MrxskAuBLnga
      F6AQsopsJe85gdBjkFktwl7tIvytTBlB7rJtRKtamKf9qLp5Q5WCveGbZEXLnO8w
      BcpM9W+AYjj+grbfiI8THNa9nIMwAzs2jCgZo8N5dOUVBTiY7fj+ZHfx7K+oFeBf
      T49G6LMR9kglODf+179aDETIo8hWh9w49OsxNBsUTzAk7QbYjpj6JGMMHYklSFm9
      yg08ssYTtgH3+J9QQIXDYvz3JYnpjHiPkHL4wLfxfR0L0PEN2euBbcsjNqoGlZcU
      hD/mQ+8yLARUSWyFtuecWA7ZUy9Zjs5jWC47lLSoiHjz+cWtGePoLim0iaYfd0S/
      DRDkW47e19mgUGoZD1mHSRytEUr3gmBx2VpRBg+K/0w9MS+zT1abLGkrTJnI+Qfw
      OJkSXv3EEjqUPgk=
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIElzCCAv+gAwIBAgIRAPY6eHmYK1TMyGdjgSAsx4MwDQYJKoZIhvcNAQELBQAw
      gaMxHjAcBgNVBAoTFW1rY2VydCBkZXZlbG9wbWVudCBDQTE8MDoGA1UECwwzcmFj
      aG1hdGFkaGllQENyYWNrZXJzLU1hY0Jvb2subG9jYWwgKFJhY2htYXQgQWRoaWUp
      MUMwQQYDVQQDDDpta2NlcnQgcmFjaG1hdGFkaGllQENyYWNrZXJzLU1hY0Jvb2su
      bG9jYWwgKFJhY2htYXQgQWRoaWUpMB4XDTI1MDIxNjA1Mzc1MVoXDTI3MDUxNjA1
      Mzc1MVowZzEnMCUGA1UEChMebWtjZXJ0IGRldmVsb3BtZW50IGNlcnRpZmljYXRl
      MTwwOgYDVQQLDDNyYWNobWF0YWRoaWVAQ3JhY2tlcnMtTWFjQm9vay5sb2NhbCAo
      UmFjaG1hdCBBZGhpZSkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDW
      PE0V2HIJFEVzeJtYvO4nkOei6tDaJkwLgDVigEqIya8YB2ynIsTia+JfU6aHIoLr
      gfe2l7I755BrIiZqPwm81othDtewUWYK1uE6St9cdUmkFmxC+MqdJ/JmJrCpBOWU
      a8AYWztMAOE9wG+aYOFRQC90wYSgTwHEh6/ljuGUZd0smOQ7zb4ckQMa/PpVJq+L
      AYrxUAkgVxKzXN2luWCBTBKvfK29kHHa3ZBbAAYT76yOyrxI7OigUThi56MCyqDM
      wuAKCJz8uP4Jy9z3z587W9ANrZe0x76WDnZHkoAWlSBU8272KkD/kaV6Ahy5zySo
      bx3uSVszweid9Ex1+51hAgMBAAGjgYAwfjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
      BAwwCgYIKwYBBQUHAwEwHwYDVR0jBBgwFoAUqng0T6Bg7Y6V2pUkkB4caq6pQDUw
      NgYDVR0RBC8wLYIrYm9va2NvbW1lbnQtZGV2LWJvb2tyZXZpZXcuYXBwcy1jcmMu
      dGVzdGluZzANBgkqhkiG9w0BAQsFAAOCAYEAnxtEz/Uzu4dxRLgGIsDO4hEQT/eB
      eGIniC0j5GP0QnsTz2rno4d3dehXK6UXDFatHpoZB5KkFe1JaWko0g3R1YbKISgW
      zRmMhKGeexhYj8c/AIu+Jt0w3M1Rzl/MaMQ+Alky1kfletqrjIopBufSFyzPL4VI
      nSmH+aFH6PocPsgG2q/cEJ4fIN+EJfSBSb+prduw7WAhrzGsHBxBen+k/t+cwDLq
      eJYflBGzcAiOYgQDBbBlM6vb98m3+ItL+KVJLgb6b5f+B9ibXDK+3xVLLWYmrDTT
      SSQ/acuaVlJpFqHsghs0C1Qw/NS2ejUbIs1SigSBAE7QuPvV7pMcYpmsGgzHX52G
      Oi2lxkaxDT8/SGSgouIsSaxo5yMFWuaRbvDrs/u2DcBl+LRRwqT+BtudT1I2DnkD
      6JLewkblPbJ277s6YqO1cSxp9/vyWJ/GX1yyDXeN4Ee+EcYooq8ZkXkBCkn6kV88
      jSEro7zh+xFcK2XCtM2WptjhjC4qhkK7HCUT
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: None
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDWPE0V2HIJFEVz
      eJtYvO4nkOei6tDaJkwLgDVigEqIya8YB2ynIsTia+JfU6aHIoLrgfe2l7I755Br
      IiZqPwm81othDtewUWYK1uE6St9cdUmkFmxC+MqdJ/JmJrCpBOWUa8AYWztMAOE9
      wG+aYOFRQC90wYSgTwHEh6/ljuGUZd0smOQ7zb4ckQMa/PpVJq+LAYrxUAkgVxKz
      XN2luWCBTBKvfK29kHHa3ZBbAAYT76yOyrxI7OigUThi56MCyqDMwuAKCJz8uP4J
      y9z3z587W9ANrZe0x76WDnZHkoAWlSBU8272KkD/kaV6Ahy5zySobx3uSVszweid
      9Ex1+51hAgMBAAECggEBAINCqxBJb4U0kGDxcmzqRRik5eeh65jdghZB1XOmmwQ4
      XjlgwyecW/lGlIpHnG6LrJ9TIE0VoLSnaorZf6P1P6gd44PyLiDvno/hnFm06imi
      Cx6oRmi6OpoTkacY6YCFaYyIgEfsDebBW0AUmcyCs0qvAuSMdRArmC+r2w/RfVEI
      AXgvRfBBhH2/ZIjb1YoJMwF73iFJvz9Rmg0uQ3EeMxJvQa2JQ0XE9X2zrQlEzvlY
      KfLKET8JVq519FcLCL8H14EC7ykWA5kGfDQ3i08H3gqQCY/yQfwjos5F03WXsNrj
      yBlIPWQ0UroRqoGW10ZmhLgcW5FDSUh87lrUqR5js2kCgYEA7mS+fFK7uqcjBbfY
      ND8vhKVSFiL4uvtMdFEigHu763/Xhc1obmf2C80ImlkTP2u83Te+GmHs8Xtwz1ey
      3vRp8LFidvFc5hf8dUMAj8fg2LlMtpg6mMq3SNKfDbSQE+F24rzydc6TSSaF68Cf
      ZCtMLERbqhJZmlXcy4k4aZF9/lcCgYEA5g7OphY80ES8ExZ1E5LrcV38EPI/lcxK
      LFjq9cVWMH2yspHbbJfx0tcv0bmkGCJlW+mowRwKOAwmBnKH3WeRCTRxLUgfRYS/
      QVDjWk3jzYSvZzA9CMsyXxSDohWl360P1qlhkeHYFMOvfpcXACHjTxsYfcGZuDKV
      zC2Q9E23/wcCgYEA0eLY4tRke/1TFGG8dKN8zqhPETZRDy7ZLT+RxNUrqjewJRmn
      7CyTr+ggvuPV0mykp4/AS7ITzrgDpklsLme6LjO+oUH3rI1JtGP9RpmQGL9sDwcP
      8B3qKK9nYcWrZBWJei8ouRfbDPhhyCKbMrH8Kq00lxP416zo7Dov9KIn75kCgYAk
      cq4ctCM4X9toLsOnsTwp/tjjmm2mfvI1anT3MSeBkTiRf/hCkSQX4k3KLV4pELH8
      SN2akqWv0YToupZ55mGdErjnkqiZq/ldEMKkWPjBY8ciUwsobIDzfV2JfWKFOHbs
      7HLv2NcSGxqftLJJLBVGQCW2Lsj63NDMw19WxUVkWwKBgFW8kFjZAurch70ZuBtb
      x0lajLFokpnLgDiLVJcOo4TRKRFV/vz4FkxECV/I5d1uXCbGC35ssg4K1oVnEHJ/
      vogJS39Jj+3v7eSy/xjHQw2hdYbJhvpqDwACXXE5Vri+9AXik3LBdYV9rwKtn9sx
      FNunLHjSuAtTwxQCibzmegpN
      -----END PRIVATE KEY-----
    termination: edge
