apiVersion: v1
kind: Secret
metadata:
  name: holder-secret
  namespace: bookreview-dev
data:
  id: ZGUzMDM3YzQtOTYxMC1mNTZmLWY5NTEtYTE4ODlhOGI0ZjRjCg==
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: bookreview-dev
  name: bookreview-dev-vault-connection
spec:
  address: https://172.21.53.100:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: bookreview-dev
  name: bookreview-dev-vault-auth
spec:
  vaultConnectionRef: bookreview-dev-vault-connection
  method: appRole
  mount: approle-k8s
  namespace: admin
  appRole:
    roleId: 5fe78376-5232-7765-5ac4-5a62c5f64517
    secretRef: holder-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: bookreview-dev
  name: bookreview-dev-comment-kv
spec:
  vaultAuthRef: bookreview-dev-vault-auth
  mount: comment-dev
  type: kv-v2
  path: webapp/config
  refreshAfter: 5s
  namespace: admin
  destination:
    create: true
    name: comment-secret-deployment
  rolloutRestartTargets:
  - kind: Deployment
    name: comment